### ISSUE TITLE
Usuário logado dentro do model

### ISSUE THREAD

**Issue by Marlysson** [npdscodes/mural-api#9]
Verificar como obter o usuário atualmente logado para adicioná-lo associado à resposta feita , seja a um comentário ou a uma resposta.
- [ ] Passando um `request.user` para o construtor do modelo
- [ ] Adicionando um parâmetro ao método `responder` para representar o user logado ( request.user)

**Comment by rogerio410** [comment]
@Marlysson oso Serializers no DRF tem comportamento semelhante aos Forms do Django. Assim um serializers tem Atributos e alguns Métodos que podem ser subrescritos. Métodos como `.save()`, `.update()`, `.create()`, `.validade`, `.validade_<fildname>` onde podemos trabalhar exatamente como nos Forms sejam essa Form Normal ou Model Form, Serializers Normal Ou ModelSerializer. 

Assim ao implementar esses métodos você pode acessar o `request` atual por meio do `request = self.context['request']` ou `request = self.context.get('request')`

blz?

**Comment by rogerio410** [comment]
Veja esse exemplo:

``` python
class SprintSerializer(serializers.ModelSerializer):

    links = serializers.SerializerMethodField()

    class Meta:
        model = Sprint
        fields = ('id', 'name', 'description', 'end', 'links', )

    def get_links(self, obj):
        request = self.context['request']
        return {
            'self': reverse('sprint-detail',
                            kwargs={'pk': obj.pk}),
            'tasks': reverse('task-list') + '?sprint={}'.format(obj.pk),
        }
```

ou este outro:

``` python
class VoucherAddSerializer(serializers.Serializer):
    vouchercode = serializers.CharField(max_length=128, required=True)

    def validate(self, attrs):
        # oscar expects this always to be uppercase.
        attrs['vouchercode'] = attrs['vouchercode'].upper()

        request = self.context.get('request')
        try:
            voucher = Voucher.objects.get(code=attrs.get('vouchercode'))

            # check expiry date
            if not voucher.is_active():
                message = _("The '%(code)s' voucher has expired") % {
                    'code': voucher.code
                }
                raise serializers.ValidationError(message)
```

**Comment by Marlysson** [comment]
Então pega o contexto da requisição usando o DRF e nesse contexto tem o user.. que será colocado dentro do modelo para ser salvo..

**Comment by rogerio410** [comment]
Exato.
